dxw/tech-team-rfcs

- .gitignore
- .hound.yml
- .remarkrc
- README.md
- package-lock.json
- package.json
- rfc-000-template.md
This is a similar setup to how we lint the playbook.
~Hound still needs setting up and, if this repo goes private, paying for. This may require a [GitHub admin](http://help.houndci.com/en/articles/67600-why-doesn-t-hound-list-a-repo-on-which-i-m-a-collaborator).~ Hound is now enabled for new PRs. Until this (or similar) is merged, it's not checking Markdown.
> Lint using Remark and Hound

- README.md
* As the documentation describes this attempts to make it clear how we can conclude wether a decision has consensus or not.
* GitHub settings currently have a minimum of 3 approvals required. Using this as our source of approval rather than :thumbs-up: emojis will offer a single source of truth for consensus. In the same way request for changes over :thumbs-down: will be more helpful as it gives the person a natural place to leave comment beside their opinion.
* Using approvals and request for changes will also serve to document a reversal of decision whereas it will be impossible to track the movement in emojis as a decision is ammended.
> (feature) Document how to use GitHub PR review tooling

- .hound.yml
- .remarkrc.hound
Hound doesn't appear to install any dependencies, causing errors when linting.
> Stop using the extended packages for linting on Hound

- rfc-013-use-docker-to-deploy-and-run-applications-in-containers.md
- rfc-019-use-changelogs-to-track-changes.md
- rfc-021-use-auth0-as-the-default-auth-provider.md
Following the addition of automated linting to commits, this PR brings existing RFCs up to passing standard. There are no content changes.
> Update existing RFCs to pass automatic linting

- rfc-023-use-scripts-to-rule-them-all.md
We should adopt the [Scripts To Rule Them All](https://github.com/github/scripts-to-rule-them-all) pattern which GitHub uses to standardise the names of common scripts between various applications.
Standardising the names, locations and behaviour of these scripts makes the experience of developing, testing and running applications more consistent.
This RFC encourages the adoption of the pattern, and explicitly states that projects SHOULD have scripts for bootstrapping, testing and starting a server, and MAY have other scripts for tasks such as setup, update, opening a console and running tests in a CI environment.
> Use the "Scripts To Rule Them All" pattern for common tasks

- rfc-023-use-scripts-to-rule-them-all.md
Atom did not correctly place a line break during automatic hard breaking.
> Fix incorrect formatting in RFC 023

- rfc-018-our-decision-making-process-is-public.md
This proposal comes straight from a now [closed issue](https://github.com/dxw/tech-team-rfcs/issues/2) where we discussed the issue with several members of the team.
The issue debates the position of being open by default and that being open makes things better. 
This proposal seeks to document why this repository is currently public.
There were a few concerns raised around the need to sometimes include sensitive information around incidents. I think we can make use of tech forums to discuss sensitive details offline if we need to as a first pass, if that fails we can make it private later. It is much harder to go in the other direction of making a private repo public.
If we do no approve this I propose we need another RFC that documents the decision to make it private.
> Document why our RFC process is public

- rfc-028-adopt-a-code-of-conduct.md
This comes from a conversation at the diversity and inclusion group.
https://trello.com/c/7NR54D1Z/78-adopt-a-code-of-conduct-by-default-for-our-code
> Adopt a code of conduct for public repositories

- rfc-029-source-code-should-be-open-source-by-default.md
This replaces https://github.com/dxw/playbook/issues/12.
This is a first draft – I'll sort the writing out once we’ve agreed that the content is fine. I'd like to hear people's thoughts on this and whether there's anything else I need to address.
> Source code should be public by default

- rfc-088-optimise-dependabot-config-files-in-govpress-repos.md
This PR documents and formalises the approach we are taking to Dependabot configuration in GovPress repos. That is, broadly speaking:
- Dependabot must raise alerts and opens PR for any production vulnerabilities
- Alerts/PRs should not be raised for NPM development vulnerabilities, as these pose a low risk and generate too much noise to be manageable
- Other development vulnerabilities should be alerted about, but do not have to be
I'm unsure if this should remain a GovPress-specific RFC, or whether it would be worth redrafting this to address exclusively  how we handle NPM development dependencies in Dependabot across dxw, giving it a tighter focus but a wider application.
Any feedback on the above, or anything else in the PR, much appreciated!
> Optimise Dependabot rules in GovPress repos

- .github/workflows/check-labels.yml
Without this, it’s impossible to get this action to run again after pushing to the branch without adding/removing a label, meaning the PR can’t be merged, even if all the other prerequisites are met.
> Add `synchronize` option to check-for-new action

- .remarkrc
- package-lock.json
- package.json
This library started failing CI incorrectly as it stated a number of links no longer worked. When checked manually they all resolved:
```
rfc-087-use-libraries-where-possible.md
68:3-68:55  warning  Link to https://opensource.org/licenses/Apache-2.0 is dead    no-dead-urls  remark-lint
70:5-70:61  warning  Link to https://opensource.org/licenses/BSD-3-Clause is dead  no-dead-urls  remark-lint
71:5-71:61  warning  Link to https://opensource.org/licenses/BSD-2-Clause is dead  no-dead-urls  remark-lint
72:5-72:49  warning  Link to https://opensource.org/licenses/0BSD is dead          no-dead-urls  remark-lint
73:3-73:45  warning  Link to https://opensource.org/licenses/ISC is dead           no-dead-urls  remark-lint
74:3-74:49  warning  Link to https://opensource.org/licenses/MPL-2.0 is dead …
```
> Remove no dead links checker after false positives

- README.md
This commit adds some detail to the proposer instructions in the repo documentation, and suggests that proposers post to the relevent GovPress channel, if appropriate.
> Readme references GovPress Slack channel

- README.md
To help with reviewing the list of adopted RFCs at a glance, provide a list in the `README.md` file. Currently, depending on a users browser window, you might be presented with something like:
If you're getting familiar with the RFCs and want to see them at a glance, and choose one for selected reading, providing a list in the `README` makes this easier to digest. It looks like this:
> Add list of adopted RFCs to the repo README.md

- .github/workflows/check-approvals.yml
- Add a workflow action for checking PR type and checking number of approvals based on that
- So that for RFC PRs we can set required approvals to 3. An RFC PR is any that doesn't have a `tooling` label.
- For tooling related PRs we can set required approvals to 1. A tooling PR is one that has the `tooling` label.
This would resolve #17 . Once merged, we would be able to remove the branch protection setting for number of approvals, and let the workflow handle it instead.
It would look like this in the "Checks" area of a PR:
In this example, it's a Tooling PR with no approvals.
> Allow different approval counts based on PR type (RFC or Tooling)

- .github/workflows/label-pull-request.yml
- renovate.json
This is so that we can bypass the 14 day wait for new RFC PRS before they can be merged. 
renovate created PRs will have the `dependencies` label automatically added to them. Any PRs that have a label already attached will not be treated as an RFC.
> renovate PRs will not have 'new' label auto-added

- .github/workflows/check-approvals.yml
Fixes #239 
Previously the approvals workflows were set up to be triggered by either a `pull_request` or `pull_request_review` trigger. Each time a workflow is run for one of these triggers, it will not be run for the other. This would mean that when a previous action had run and failed (for example) for a `pull_request` trigger, it would remain failed even after a `pull_request_review` action had run and succeeded. That would mean there was an outstanding check failing even if we had the correct number of approvals. The only way to fix it would be to manually re-run that failed job, which is not ideal.
We will now only check for approval counts after a `pull_request_review` trigger - which is the most essential. The repo has been setup now with a minimum of 1 approval, so a PR can't …
> Ensure approval check runs after PR reviews

- README.md
- tools-and-technology/rfc-035-use-linting-tools-across-all-our-projects.md
The use of "standard" in the linting RFC has caused some confusion among developers. While the title is `Use standard` not `Use Standard` and later it says `meets a standard` not `meet Standard`, when scanning the RFC it's easy to mistake this for suggesting we use the specific set of linters called Standard (for languages where they exist, i.e. JavaScript/TypeScript and Ruby)
This removes use of the word "standard" except where referencing linters called Standard, and provides examples of other linters that we also use within the JavaScript/TypeScript domain
> Clarify linting RFC

- README.md
- ways-of-working/rfc-244-use-automated-accessibility-checks-in-feature-tests.md
Accessibility is core to our mission, but it's easy to let it slip in moments of pressure, or to treat it as something to fix just before going live. Tools exist that can help us integrate accessibility checks into our feature tests without relying on memory or time, alerting us as soon as something goes wrong. We should use these tools where possible to make building accessible services easier.
Manual testing is still a necessary complement to automated checks, for which brief recommendations are made on minimum expectations.
> Use accessibility checks in feature tests

- .github/dependabot.yml
- renovate.json
We have a new [standard config](https://github.com/dxw/renovate-config) we're trying out for Renovate, so all our internal repos behave the same way.
This also disables dependabot dependency updates, since Renovate handles them.
This config does have a difference from the base one, in that it also adds the `tooling` tag. This means the needed reviews will be reduced from three to one (although Renovate will bypass review for automerging minor updates anyway).
> Swap renovate config to use internal standard

- ways-of-working/rfc-244-use-automated-accessibility-checks-in-feature-tests.md
These currently redirect to a section landing page since a content restructure. [An issue has been raised][1] to fix this, but this addresses the issue here
Note: this isn't really tooling, but I've labelled it that since it's a fix and shouldn't require three approvals (the tooling label sets the [required approvals][2] to one)
[1]: https://github.com/dxw/playbook/issues/1198
[2]: https://github.com/dxw/tech-team-rfcs/blob/main/.github/workflows/check-approvals.yml
> Fix playbook links in RFC244

- .github/workflows/check-approvals.yml
Tooling PRs should only require one approval, per this action. However, this action would only update the required number of approvals on submission of a new review (I think), meaning that if the 'tooling' label was added after an approving review, the required number of approvals wouldn't be updated and the PR would still be blocked
This sets the action to trigger whenever labels are changed
Example of where this is an issue: #255
> Run check approvals on PR changes

- ways-of-working/rfc-244-use-automated-accessibility-checks-in-feature-tests.md
This is an update to the 'example pull request' link for setting up accessibility tests in Playwright using the axe-core package.
Have updated with a later PR in the project, as it shows an example set up of a custom assertion using the accessibility scanner, which used in a number of tests.
The original PR linked showed the use of the scanner used in one test, which is not as useful to developers looking to adopt the approach in their tests.
We have included a link to the first PR in this one as a reference.
> Update example pull request link for playwright
